path: ./dataset_hand_success # 数据集根目录
train: train/images # 训练集目录名
val: valid/images # 验证集目录名
test: test/images

task: pose #任务类型为 pose
loss: CIou


#nc: 2 # 类别数
#names: ['left_hand', 'right_hand']

nc: 1
names: ['hand']
kpt_shape: [21, 3] # 关键点数量, 维度数量 (2 表示 x,y 或 3 表示 x,y,可见性)
flip_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] # 关键点