path: ./dataset1 # 数据集根目录
train: train/images # 训练集目录名
val: valid/images # 验证集目录名
nc: 1 # 类别数
names: [ 'hand' ] # 类别名称
kpt_shape: [11, 3] # 关键点数量, 维度数量 (2 表示 x,y 或 3 表示 x,y,可见性)
flip_idx: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # 关键点
#roboflow:
#  workspace: crabapples
#  project: pose-label-qi4gq
#  version: 1
#  license: CC BY 4.0
#  url: https://universe.r
